services:
  - type: web
    name: bgcgeeks-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_SECRET_KEY
        sync: false
      - key: ACTIVATION_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: REFRESH_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SERVICE
        sync: false
      - key: SMTP_MAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VDPCIPHER_API_SECRET
        sync: false